#!/bin/sh
export PYTHONPATH=/home/s3066193/.local/lib/python2.7/site-packages
COORDINATOR_ID=`cat /lustre/scratch2/s3066193/hyperdexdata/coordinator_id`
python2.7 kv_test.py --kv_coordinator=$COORDINATOR_ID
